import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { ConversationProvider } from "./context/ConversationContext";
import { AuthProvider } from "./context/AuthContext";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

// const robotoMono = Roboto_Mono({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-roboto-mono',
// })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${inter.variable} antialiased min-h-full flex flex-col`}
      >
      <AuthProvider>
        <Header />
        <main className="flex-1">
            <ConversationProvider >
              {children}
            </ConversationProvider>
        </main>
        <Footer />
      </AuthProvider>
      </body>
    </html>
  );
}
